[package]
name = "performant-markdown-to-wikilink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
walkdir = "2.3.1"
pathdiff = "0.2"